services:

  scraper:
    build: .
    command: python src/ingestion/imobiliare_scraper.py
    volumes:
      - ./data:/app/data

  transform:
    build: .
    command: python src/pipeline/01_Bronze_to_Silver.py
    volumes:
      - ./data:/app/data
    depends_on:
      scraper:
        condition: service_completed_successfully

  gold:
    build: .
    command: python src/pipeline/02_Silver_to_Gold.py
    volumes:
      - ./data:/app/data
    depends_on:
      transform:
        condition: service_completed_successfully
